version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/app  # Map the entire project directory to /app inside the container
      - ./uploads:/app/uploads
